import Link from "next/link";
import { ArrowRight, BookOpen, Bot, BriefcaseBusiness, CheckCircle2, FileText, Gauge, Sparkles } from "lucide-react";
const features = [
  [BookOpen,"A Clear Path to VA Work","Know what to learn next, build practical skills, and move forward with a guided path."],
  [BriefcaseBusiness,"Practice Real Workflows","Build confidence through realistic email, calendar, file, research, and client-work simulations."],
  [FileText,"Ready-to-Use Tools","Work faster with practical templates, SOPs, checklists, and repeatable workflows."],
  [Bot,"An AI Guide When You Need It","Get step-by-step help as you learn, practice, and work through business tasks."],
  [Gauge,"Plans That Match Your Progress","Start free, see your usage clearly, and upgrade when you need more capacity."],
  [Sparkles,"Business Access & Promos","Use owner-issued promotions and invitations for controlled access and added usage."],
] as const;
export default function Home() { return <main className="landing"><nav><div className="brand"><span className="brandmark">AI</span> BUSINESS</div><div className="navlinks"><Link href="/login">Log in</Link><Link className="button small" href="/create-account">Create your free account <ArrowRight size={16}/></Link></div></nav><section className="hero"><div className="eyebrow">YOUR PRACTICAL VA WORKSPACE</div><h1>Turn uncertainty into<br/><span>practical VA skills.</span><br/>Build work you can offer.</h1><p>AI BUSINESS gives aspiring virtual assistants a clear learning path, realistic practice, reusable business tools, and an AI guide—so you can spend less time wondering where to start and more time learning how to work.</p><div className="actions"><Link className="button" href="/create-account">Start free and explore <ArrowRight size={18}/></Link><Link className="textlink" href="/guide">Explore the VA path</Link></div><div className="trust"><CheckCircle2 size={16}/> Free to start · Upgrade when you need more</div></section><section className="features">{features.map(([Icon,title,desc])=><article key={title}><div className="icon"><Icon size={20}/></div><h3>{title}</h3><p>{desc}</p></article>)}</section><section className="cta"><div><div className="eyebrow">READY WHEN YOU ARE</div><h2>Start with the skills. Build toward the work.</h2><p>Create your account, choose your path, and take your first practical step today.</p></div><Link className="button" href="/create-account">Create your free account <ArrowRight size={18}/></Link></section><footer>AI BUSINESS · Practical tools and guided learning for aspiring VAs and growing businesses.</footer></main> }
