'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Check } from 'lucide-react';
import { createClient } from '../../lib/supabase/client';

type Plan={slug:string;name:string;monthly_price:number;monthly_credits:number};
const positioning:Record<string,{title:string;description:string;points:string[]}>={
  free:{title:'Start with the essentials',description:'Explore the workspace, learn the basics, and discover how AI BUSINESS fits your goals.',points:['Guided VA learning path','Practical starter resources','A clear view of your usage']},
  starter:{title:'Build skills you can use',description:'Get more room to practice, use AI guidance, and turn learning into consistent work.',points:['More monthly AI credits','Practical workflows and practice','Built for steady skill-building']},
  pro:{title:'Work with greater capacity',description:'For users ready to do more, manage more work, and make AI BUSINESS part of their workflow.',points:['Highest monthly credit allowance','More capacity for AI-assisted work','Designed for client-ready workflows']},
};
export default function Plans(){
  const [plans,setPlans]=useState<Plan[]>([]);const [active,setActive]=useState('free');const [remaining,setRemaining]=useState(0);const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState('');
  useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const [p,b]=await Promise.all([s.from('plans').select('slug,name,monthly_price,monthly_credits').eq('active',true).order('monthly_price'),fetch('/api/billing/summary')]);setPlans(p.data??[]);if(b.ok){const j=await b.json();setActive(j.plan?.slug??'free');setRemaining(j.usage?.remaining??0)}})()},[]);
  async function choose(slug:string){if(slug==='free'||slug===active)return;setBusy(slug);setMessage('');const r=await fetch('/api/billing/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({plan_slug:slug})});const j=await r.json().catch(()=>({}));if(r.ok&&j.checkout_url){window.location.href=j.checkout_url}else setMessage(j.error||'Checkout could not be started.');setBusy(null)}
  return <main className="page"><header className="topbar"><Link className="brand" href="/">AI BUSINESS</Link><Link href="/dashboard">Dashboard</Link></header><section className="pagehero"><div className="eyebrow">PLANS & USAGE</div><h1>Choose the level of support that fits your goals.</h1><p>Start with the essentials. Upgrade when you need more practice, AI guidance, and operating capacity. Current access: <strong>{active}</strong> · {remaining} credits remaining.</p></section><section className="plans">{plans.map(x=>{const copy=positioning[x.slug]??positioning.free;return <article key={x.slug} className={x.slug==='starter'?'featured-plan':''}><span>{x.name}</span><strong>₱{x.monthly_price}<small>/month</small></strong><h2>{copy.title}</h2><p>{copy.description}</p><ul>{copy.points.map(point=><li key={point}><Check size={15}/>{point}</li>)}</ul><button className={x.slug==='starter'?'button':''} onClick={()=>choose(x.slug)} disabled={busy!==null}>{x.slug===active?'Current plan':busy===x.slug?'Opening secure checkout…':x.slug==='free'?'Start free':'Choose '+x.name+' '}<ArrowRight size={15}/></button></article>})}</section>{message&&<div className="notice error">{message}</div>}<section className="usagepanel"><h2>Your usage, clearly tracked</h2><p>{remaining} credits remain in the current billing period. Usage is enforced server-side so your allowance stays predictable.</p></section><section className="usagepanel"><h2>Have an access code?</h2><p>Owner-issued promo codes can grant credits or time-limited plan access.</p><Link className="button" href="/promos">Redeem a promo code <ArrowRight size={16}/></Link></section></main>;
}
