'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { createClient } from '../../lib/supabase/client';

type Plan={slug:string;name:string;monthly_price:number;monthly_credits:number};
export default function Plans(){
  const [plans,setPlans]=useState<Plan[]>([]);const [active,setActive]=useState('free');const [remaining,setRemaining]=useState(0);const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState('');
  useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const [p,b]=await Promise.all([s.from('plans').select('slug,name,monthly_price,monthly_credits').eq('active',true).order('monthly_price'),fetch('/api/billing/summary')]);setPlans(p.data??[]);if(b.ok){const j=await b.json();setActive(j.plan?.slug??'free');setRemaining(j.usage?.remaining??0)}})()},[]);
  async function choose(slug:string){if(slug==='free'||slug===active)return;setBusy(slug);setMessage('');const r=await fetch('/api/billing/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({plan_slug:slug})});const j=await r.json().catch(()=>({}));if(r.ok&&j.checkout_url){window.location.href=j.checkout_url}else setMessage(j.error||'Checkout could not be started.');setBusy(null)}
  return <main className="page"><header className="topbar"><Link className="brand" href="/">AI BUSINESS</Link><Link href="/dashboard">Dashboard</Link></header><section className="pagehero"><div className="eyebrow">PLANS & USAGE</div><h1>Choose the workspace that fits your stage.</h1><p>Current access: <strong>{active}</strong>. {remaining} credits remaining.</p></section><section className="plans">{plans.map(x=><article key={x.slug}><span>{x.name}</span><strong>₱{x.monthly_price}</strong><h2>{x.slug==='free'?'Start learning':x.slug==='starter'?'Build your skills':'Get client-ready'}</h2><p>{x.monthly_credits} monthly credits for AI and metered operations.</p><button className={x.slug==='starter'?'button':''} onClick={()=>choose(x.slug)} disabled={busy!==null}>{x.slug===active?'Current plan':busy===x.slug?'Opening checkout…':'Choose '+x.name}</button></article>)}</section>{message&&<div className="notice error">{message}</div>}<section className="usagepanel"><h2>Usage</h2><p>{remaining} credits remain in the current billing period. Usage is enforced server-side.</p></section><section className="usagepanel"><h2>Promo access</h2><p>Owner-issued promo codes can grant credits or time-limited plan access.</p><Link className="button" href="/promos">Redeem a promo code</Link></section></main>;
}
