'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { createClient } from '../../lib/supabase/client';

type Item = { id: string; title: string; description: string; skills: string[] };
export default function Portfolio() {
  const [items, setItems] = useState<Item[]>([]);
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [skills, setSkills] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { void load(); }, []);
  async function load() { const s=createClient(); const {data:{user}}=await s.auth.getUser(); if(!user)return; const {data,error}=await s.from('portfolio_items').select('id,title,description,skills').eq('user_id',user.id).order('created_at',{ascending:false}); if(error)setMessage(error.message); else setItems(data??[]); }
  async function add(e:React.FormEvent) { e.preventDefault(); if(!title.trim())return; setBusy(true); setMessage(''); const s=createClient(); const {data:{user}}=await s.auth.getUser(); if(!user){setMessage('Please log in first.');setBusy(false);return;} const {error}=await s.from('portfolio_items').insert({user_id:user.id,title:title.trim(),description:description.trim(),skills:skills.split(',').map(x=>x.trim()).filter(Boolean)}); if(error)setMessage(error.message); else {setTitle('');setDescription('');setSkills('');setMessage('Portfolio item saved.');await load();} setBusy(false); }
  async function remove(id:string){ const s=createClient(); const {error}=await s.from('portfolio_items').delete().eq('id',id); if(error)setMessage(error.message); else await load(); }
  return <main className="page"><header className="topbar"><Link className="brand" href="/dashboard">AI BUSINESS</Link><Link href="/practice">Practice</Link></header><section className="pagehero"><div className="eyebrow">PORTFOLIO</div><h1>Turn practice into proof.</h1><p>Your portfolio is blank by design. Add only your own work, skills, and service examples.</p></section><form className="formpanel" onSubmit={add}><h2>Add a portfolio item</h2><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Inbox management simulation" required /></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What you did, the process you followed, and the outcome." /></label><label>Skills<input value={skills} onChange={e=>setSkills(e.target.value)} placeholder="Email, research, spreadsheets" /></label><button className="button" disabled={busy}>{busy?'Saving…':'Save portfolio item'}</button>{message&&<div className="notice">{message}</div>}</form><section className="listgrid" style={{marginTop:15}}>{items.map(item=><article key={item.id}><span>PORTFOLIO ITEM</span><h2>{item.title}</h2><p>{item.description||'No description yet.'}</p>{item.skills.length>0&&<p><strong>Skills:</strong> {item.skills.join(', ')}</p>}<button onClick={()=>void remove(item.id)}>Delete</button></article>)}{!items.length&&<article><span>BLANK START</span><h2>No portfolio items yet</h2><p>Complete a practice task, then document your own result here.</p></article>}</section></main>;
}
