-- AI BUSINESS incremental migration: monthly credits, sandbox checkout, and admin access.
create table if not exists public.credit_grants (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, source text not null check(source in ('monthly_plan','promo','manual')), units integer not null check(units>0), valid_from timestamptz not null, valid_until timestamptz not null, metadata jsonb not null default '{}', created_at timestamptz not null default now(), unique(user_id,source,valid_from));
create table if not exists public.billing_checkout_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, plan_id uuid not null references public.plans(id), provider text not null default 'mock', provider_session_id text unique, status text not null default 'pending' check(status in ('pending','paid','canceled','expired')), amount numeric(12,2) not null, created_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists public.business_workspaces (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null, description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.business_tasks (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, workspace_id uuid references public.business_workspaces(id) on delete cascade, title text not null, description text, status text not null default 'todo' check(status in ('todo','in_progress','review','done')), priority text not null default 'normal' check(priority in ('low','normal','high','urgent')), assigned_to uuid references auth.users(id) on delete set null, due_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.business_team_members (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, workspace_id uuid references public.business_workspaces(id) on delete cascade, member_user_id uuid references auth.users(id) on delete cascade, email text not null, role text not null default 'member' check(role in ('owner','manager','member','va')), status text not null default 'invited' check(status in ('invited','active','removed')), created_at timestamptz not null default now(), unique(workspace_id,email));

alter table public.credit_grants enable row level security;
alter table public.billing_checkout_sessions enable row level security;
alter table public.business_workspaces enable row level security;
alter table public.business_tasks enable row level security;
alter table public.business_team_members enable row level security;

drop policy if exists "credit grants own" on public.credit_grants;
create policy "credit grants own" on public.credit_grants for select to authenticated using ((select auth.uid())=user_id);
drop policy if exists "credit grants admin read" on public.credit_grants;
create policy "credit grants admin read" on public.credit_grants for select to authenticated using ((select role from public.profiles where id=(select auth.uid()))='admin');
drop policy if exists "checkout own" on public.billing_checkout_sessions;
create policy "checkout own" on public.billing_checkout_sessions for select to authenticated using ((select auth.uid())=user_id);
drop policy if exists "usage admin read" on public.usage_events;
create policy "usage admin read" on public.usage_events for select to authenticated using ((select role from public.profiles where id=(select auth.uid()))='admin');
drop policy if exists "promo admin read" on public.promo_codes;
create policy "promo admin read" on public.promo_codes for select to authenticated using ((select role from public.profiles where id=(select auth.uid()))='admin');
drop policy if exists "promo admin insert" on public.promo_codes;
create policy "promo admin insert" on public.promo_codes for insert to authenticated with check ((select role from public.profiles where id=(select auth.uid()))='admin');
drop policy if exists "promo admin update" on public.promo_codes;
create policy "promo admin update" on public.promo_codes for update to authenticated using ((select role from public.profiles where id=(select auth.uid()))='admin') with check ((select role from public.profiles where id=(select auth.uid()))='admin');
drop policy if exists "promo redemption admin read" on public.promo_redemptions;
create policy "promo redemption admin read" on public.promo_redemptions for select to authenticated using ((select role from public.profiles where id=(select auth.uid()))='admin');
drop policy if exists "subscription admin read" on public.subscriptions;
create policy "subscription admin read" on public.subscriptions for select to authenticated using ((select role from public.profiles where id=(select auth.uid()))='admin');

create or replace function public.create_mock_checkout(p_plan_slug text) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid(); p public.plans; v_id uuid; begin if v_user is null then raise exception 'Unauthorized'; end if; select * into p from public.plans where slug=lower(trim(p_plan_slug)) and active=true limit 1; if not found then raise exception 'Plan not found'; end if; if p.slug='free' then return jsonb_build_object('provider','free','checkout_url','/dashboard'); end if; insert into public.billing_checkout_sessions(user_id,plan_id,provider,provider_session_id,amount,status) values(v_user,p.id,'mock','mock_'||gen_random_uuid()::text,p.monthly_price,'pending') returning id into v_id; return jsonb_build_object('provider','mock','session_id',v_id,'checkout_url','/billing/test-checkout?session='||v_id::text); end; $$;
revoke all on function public.create_mock_checkout(text) from public;
revoke execute on function public.create_mock_checkout(text) from anon;
grant execute on function public.create_mock_checkout(text) to authenticated;

create or replace function public.complete_mock_checkout(p_session uuid) returns jsonb language plpgsql security definer set search_path=public as $$ declare s public.billing_checkout_sessions; now_ts timestamptz:=now(); begin if auth.uid() is null then raise exception 'Unauthorized'; end if; select * into s from public.billing_checkout_sessions where id=p_session and user_id=auth.uid() for update; if not found then raise exception 'Checkout session not found'; end if; if s.provider<>'mock' or s.status<>'pending' then raise exception 'Checkout session is not payable'; end if; update public.subscriptions set status='expired',ends_at=now_ts where user_id=auth.uid() and status in ('active','trialing'); insert into public.subscriptions(user_id,plan_id,status,starts_at,ends_at) values(auth.uid(),s.plan_id,'active',now_ts,now_ts+interval '30 days'); update public.billing_checkout_sessions set status='paid',completed_at=now_ts where id=s.id; return jsonb_build_object('ok',true,'session_id',s.id,'status','paid'); end; $$;
revoke all on function public.complete_mock_checkout(uuid) from public;
revoke execute on function public.complete_mock_checkout(uuid) from anon;
grant execute on function public.complete_mock_checkout(uuid) to authenticated;

create or replace function public.ensure_monthly_credit_grant(p_user_id uuid) returns void language plpgsql security definer set search_path=public as $$ declare v_start timestamptz; v_end timestamptz; v_credits integer; begin if p_user_id is null or p_user_id<>auth.uid() then raise exception 'Unauthorized'; end if; v_start:=date_trunc('month',now()); v_end:=v_start+interval '1 month'; select coalesce((select p.monthly_credits from public.subscriptions s join public.plans p on p.id=s.plan_id where s.user_id=p_user_id and s.status in ('active','trialing') and s.starts_at<=now() and (s.ends_at is null or s.ends_at>now()) order by s.created_at desc limit 1),(select monthly_credits from public.plans where slug='free' and active=true limit 1),0) into v_credits; if v_credits>0 then insert into public.credit_grants(user_id,source,units,valid_from,valid_until,metadata) values(p_user_id,'monthly_plan',v_credits,v_start,v_end,jsonb_build_object('period',to_char(v_start,'YYYY-MM'))) on conflict(user_id,source,valid_from) do nothing; end if; end; $$;
revoke all on function public.ensure_monthly_credit_grant(uuid) from public;
revoke execute on function public.ensure_monthly_credit_grant(uuid) from anon;
grant execute on function public.ensure_monthly_credit_grant(uuid) to authenticated;

create or replace function public.consume_credits(p_units integer,p_event_type text,p_metadata jsonb default '{}') returns jsonb language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid(); v_available integer; v_units integer:=greatest(1,least(coalesce(p_units,1),100000)); v_event uuid; begin if v_user is null then raise exception 'Unauthorized'; end if; if p_event_type is null or length(trim(p_event_type))=0 then raise exception 'event_type required'; end if; perform public.ensure_monthly_credit_grant(v_user); select coalesce(sum(units),0)-coalesce((select sum(units) from public.usage_events where user_id=v_user and created_at>=date_trunc('month',now()) and created_at<date_trunc('month',now())+interval '1 month'),0) into v_available from public.credit_grants where user_id=v_user and valid_from<=now() and valid_until>now(); if v_available<v_units then raise exception 'Insufficient credits'; end if; insert into public.usage_events(user_id,event_type,units,metadata) values(v_user,trim(p_event_type),v_units,coalesce(p_metadata,'{}')) returning id into v_event; return jsonb_build_object('ok',true,'event_id',v_event,'units',v_units,'remaining',v_available-v_units); end; $$;
revoke all on function public.consume_credits(integer,text,jsonb) from public;
revoke execute on function public.consume_credits(integer,text,jsonb) from anon;
grant execute on function public.consume_credits(integer,text,jsonb) to authenticated;

create or replace function public.redeem_promo(p_code text) returns jsonb language plpgsql security definer set search_path=public as $$ declare p public.promo_codes; now_ts timestamptz:=now(); target_plan uuid; begin if auth.uid() is null then raise exception 'Unauthorized'; end if; select * into p from public.promo_codes where upper(code)=upper(trim(p_code)) and active=true for update; if not found then raise exception 'Invalid or inactive promo code'; end if; if p.starts_at>now_ts or (p.expires_at is not null and p.expires_at<now_ts) then raise exception 'Promo code is not currently valid'; end if; if p.max_redemptions is not null and p.redeemed_count>=p.max_redemptions then raise exception 'Promo redemption limit reached'; end if; if exists(select 1 from public.promo_redemptions where promo_id=p.id and user_id=auth.uid()) then raise exception 'Promo already redeemed'; end if; insert into public.promo_redemptions(promo_id,user_id) values(p.id,auth.uid()); update public.promo_codes set redeemed_count=redeemed_count+1 where id=p.id; if p.plan_id is not null then target_plan:=p.plan_id; update public.subscriptions set status='expired',ends_at=now_ts where user_id=auth.uid() and status in ('active','trialing'); insert into public.subscriptions(user_id,plan_id,status,starts_at,ends_at) values(auth.uid(),target_plan,'active',now_ts,now_ts+(p.duration_days||' days')::interval); end if; if p.credits>0 then insert into public.credit_grants(user_id,source,units,valid_from,valid_until,metadata) values(auth.uid(),'promo',p.credits,now_ts,now_ts+(p.duration_days||' days')::interval,jsonb_build_object('promo_id',p.id,'code',p.code)); end if; return jsonb_build_object('success',true,'code',p.code,'credits',p.credits,'duration_days',p.duration_days); end; $$;
revoke all on function public.redeem_promo(text) from public;
revoke execute on function public.redeem_promo(text) from anon;
grant execute on function public.redeem_promo(text) to authenticated;
